# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  version: '0.1.0-SNAPSHOT'


stages:
- stage: Version
  jobs:
  - job: read_and_update
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - bash: |
          version=$(<.version)
          echo read version is $version
          echo "##vso[task.setvariable variable=version]$version"
      name: step

    - bash: "echo $(step.version)"
    - bash: "echo $(version)"

