# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  version: '0.1.0-SNAPSHOT'


stages:
- stage: Version
  jobs:
  - job: read_and_update
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - bash: "echo $(version)"
    - bash: "echo $(Build.SourceVersionMessage)"
    - bash: |
            echo "Triggered by previous build. Breaking..."
            echo "##vso[task.setvariable variable=agent.jobstatus;]canceled"
            echo "##vso[task.complete result=Canceled;]DONE"

- stage: Version1
  dependsOn: Version
  condition: not(contains(variables['Build.SourceVersionMessage'], 'Update azure-pipelines.yml')
  jobs:
  - job: read_and_update
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - bash: "echo $(version)"
    - bash: |
          version=1
          echo $(($version+1))

- stage: Version2
  dependsOn: Version1
  condition: 
  jobs:
  - job: read_and_update
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - bash: "echo $(version)"
    - bash: |
          version=1
          echo $(($version+1))
