# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  version: '0.1.0-SNAPSHOT'


stages:
- stage: Version
  jobs:
  - job: read_and_update
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - bash: "echo $(version)"
    - bash: |
          version=$(<.version)
          echo read version is $version
          echo "##vso[task.setvariable variable=version]$version"
      name: step

    - bash: "echo $(version)"
    - bash: |
          mkdir -p $(Pipeline.Workspace)/variables
          echo $(version) > $(Pipeline.Workspace)/variables/version
          cat $(Pipeline.Workspace)/variables/version
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/variables/version'
        artifact: 'version'
        publishLocation: 'pipeline'




- stage: Check
  jobs:
  - job: read_from_prev_stage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'version'
        targetPath: '$(Pipeline.Workspace)/variables'
    - bash: |
              FOO=$(cat $(Pipeline.Workspace)/variables/version)
              echo "##vso[task.setvariable variable=version]$version"
    - bash: "echo new $(version)"
