# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml 
trigger:
-  master

variables:
  version: '0.1.0-SNAPSHOT'


stages:
- stage: Version
  jobs:
  - job: read_and_update
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - bash: |
          curl -u $(build_user):$(System.AccessToken) -H "Content-Type: application/json" --request PATCH --data '{"status":"Cancelling"}' "https://dev.azure.com/syncier/marketplace/_apis/build/builds/$(Build.BuildId)?api-version=5.1" 
          #curl -u $(build_user):$System.AccessToken -H "Content-Type: application/json" --request PATCH --data '{"status":"Cancelling"}' "https://dev.azure.com/syncier/marketplace/_apis/build/builds/$Build.BuildId?api-version=5.1" 




- stage: Version2
  dependsOn: Version
  condition: 
  jobs:
  - job: read_and_update
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - bash: "echo $(version)"
    - bash: |
          version=1
          echo $(($version+1))
